name = "Builder Pablito"
author = "P4tit0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ae2bd7a3fc361a862d52951b1ed3d1ee4e9d88d5e5eedcd06b64b6406a293ff"

[versions]
fabric = "0.18.6"
minecraft = "1.21.1"
