name = "Builder Pablito"
author = "P4tit0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c6504869e665c2f5ee03f4923feeb1f0536bc4ba313f1cdaa210a01a384be59"

[versions]
fabric = "0.18.6"
minecraft = "1.21.1"
